# Power Meter v0.9.2
#
# Power Meter with Cost Tracking.
#
# ​ Sic biscuitus disintegratum ​

substitutions:
  pulse_rate: '1000.0'
  currency: 'DKK'
  pulse_pin: '26'
  led_pin: '17'
  ha_price_sensor: 'nordpool_kwh_dk2_dkk_4_095_025'
  update_interval: '60'
  flag_update_sensors: '1'
  flag_reset_monthly: '8'
  flag_reset_daily: '16'
  flag_reset_total: '128'
  flag_reset_mask: '248'

# substitutions:
#          pulse_rate: Pulse Rate of the LED on your power-panel-meter
#            currency: Currency in which to represent costs
#           pulse_pin: GPIO pin for the pulse_meter
#             led_pin: GPIO pin for the LED
#     ha_price_sensor: entity_id of the sensor used in Home Assistant to track spot prices.
#     update_interval: Seconds (ticks in 1s interval loop) between updating sensors.
#
# Note: The flag* substitutions are instead of #defines.

esphome:
  name: power-meter
  friendly_name: 'Power Meter'
  comment: 'Power Meter with Cost Tracking'
  project:
    name: zenzay.power_meter
    version: '0.9.2'

preferences:
  flash_write_interval: 1h

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

logger:

api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

globals:
  - id: usage_total         # total kwh usage
    type: float
    restore_value: yes
    initial_value: '0'

  - id: usage_month         # monthly kwh usage
    type: float
    restore_value: yes
    initial_value: '0'

  - id: usage_day           # daily kwh usage
    type: float
    restore_value: yes
    initial_value: '0'

  - id: cost_total          # total cost
    type: float
    restore_value: yes
    initial_value: '0'

  - id: cost_month          # monthly cost
    type: float
    restore_value: yes
    initial_value: '0'

  - id: cost_day            # daily cost
    type: float
    restore_value: yes
    initial_value: '0'

  - id: uptime_secs         # uptime second counter
    type: int
    restore_value: yes
    initial_value: '0'

  - id: cost_now            # hourly cost right now
    type: float
    restore_value: no
    initial_value: '0'

  - id: price_per_kwh       # price per kwh, should be automatically imported from HA, but can also be set manually
    type: float
    restore_value: no
    initial_value: '0'

  - id: uptime_start        # uptime start timestamp
    type: int
    restore_value: no
    initial_value: '0'

  - id: op_flag             # bitmask for operational flags
    type: int
    restore_value: no
    initial_value: '0'

number:
  - platform: template
    id: pulse_rate
    name: 'Set Pulse Rate'
    unit_of_measurement: 'Pulse/kWh'
    icon: mdi:pulse
    optimistic: true
    mode: box
    min_value: 100
    max_value: 10000
    step: 100
    initial_value: 1000
    restore_value: true
    entity_category: 'config'

  - platform: template
    name: 'Set Total Usage'
    unit_of_measurement: 'kWh'
    icon: mdi:meter-electric
    optimistic: true
    mode: box
    min_value: 0
    max_value: 100000
    step: 0.001
    initial_value: 0
    disabled_by_default: true
    entity_category: 'config'
    on_value:
      lambda: id(usage_total) = x;

  - platform: template
    name: 'Set Total Cost'
    unit_of_measurement: $currency
    icon: mdi:cash-100
    optimistic: true
    mode: box
    min_value: 0
    max_value: 100000
    step: 0.001
    initial_value: 0
    disabled_by_default: true
    entity_category: 'config'
    on_value:
      lambda: id(cost_total) = x;

  - platform: template
    name: 'Set Uptime'
    unit_of_measurement: 'days'
    icon: mdi:timelapse
    optimistic: true
    mode: box
    min_value: 0
    max_value: 365
    step: 0.01
    initial_value: 0
    disabled_by_default: true
    entity_category: 'config'
    on_value:
      lambda: |-
        id(uptime_start) = 0;
        id(uptime_secs) = ceil(x * 60.0f * 60.0f * 24.0f);

  - platform: template
    name: 'Set kWh Price'
    icon: mdi:cash-100
    unit_of_measurement: '${currency}/kWh'
    optimistic: true
    mode: box
    min_value: 0
    max_value: 100
    step: 0.001
    initial_value: 0
    disabled_by_default: true
    entity_category: 'config'
    on_value:
      lambda: id(price_per_kwh) = x;

  - platform: template
    id: power_problem_level
    name: 'Set Problem Level'
    icon: mdi:alert
    unit_of_measurement: 'W'
    optimistic: true
    mode: box
    min_value: 10
    max_value: 100000
    step: 1
    initial_value: 10000
    entity_category: 'config'

light:
  - platform: neopixelbus
    variant: WS2812
    pin: $led_pin
    num_leds: 1
    type: GRB
    name: 'Power LED'
    id: power_led
    default_transition_length: 0.1s
    color_correct: [50%, 50%, 50%]
    restore_mode: ALWAYS_OFF
    entity_category: 'config'

button:
  - platform: template
    name: 'Reset Totals'
    device_class: restart
    entity_category: 'config'
    on_press:
      lambda: id(op_flag) = $flag_reset_mask;

  - platform: shutdown
    name: 'Shutdown'

binary_sensor:
  - platform: template
    name: 'Power Status'
    id: power_status_sensor
    device_class: problem
    lambda: return ( id(power_pulse_meter).state >= id(power_problem_level).state);

sensor:
  - platform: homeassistant
    id: ha_price_per_kwh
    entity_id: 'sensor.${ha_price_sensor}'
    on_value:
      lambda: id(price_per_kwh) = x;

  - platform: pulse_meter
    name: 'Power Use'
    id: power_pulse_meter
    unit_of_measurement: 'W'
    state_class: measurement
    device_class: power
    icon: mdi:flash-outline
    accuracy_decimals: 0
    pin: $pulse_pin
    internal_filter_mode: EDGE
    internal_filter: 50ms
    filters:
      - lambda: return x * (60.0f / id(pulse_rate).state ) * 1000.0f;
    total:
      id: power_pulse_total
      on_value:
        script.execute: process_power_script

  - platform: template
    name: 'Usage Total'
    id: usage_total_sensor
    unit_of_measurement: 'kWh'
    icon: mdi:meter-electric
    state_class: total_increasing
    device_class: energy
    accuracy_decimals: 3
    update_interval: never

  - platform: template
    name: 'Usage Daily'
    id: usage_day_sensor
    unit_of_measurement: 'kWh'
    icon: mdi:meter-electric
    state_class: total_increasing
    device_class: energy
    accuracy_decimals: 3
    update_interval: never

  - platform: template
    name: 'Usage Monthly'
    id: usage_month_sensor
    unit_of_measurement: 'kWh'
    icon: mdi:meter-electric
    state_class: total_increasing
    device_class: energy
    accuracy_decimals: 3
    update_interval: never

  - platform: template
    name: 'Cost Now'
    id: cost_now_sensor
    icon: mdi:cash-fast
    accuracy_decimals: 3
    unit_of_measurement: '${currency}/h'
    device_class: monetary
    update_interval: never

  - platform: template
    name: 'Cost Total'
    icon: mdi:cash-100
    id: cost_total_sensor
    unit_of_measurement: $currency
    accuracy_decimals: 3
    device_class: monetary
    update_interval: never

  - platform: template
    name: 'Cost Daily'
    icon: mdi:cash-100
    id: cost_day_sensor
    unit_of_measurement: $currency
    accuracy_decimals: 3
    device_class: monetary
    update_interval: never

  - platform: template
    name: 'Cost Monthly'
    icon: mdi:cash-100
    id: cost_month_sensor
    unit_of_measurement: $currency
    accuracy_decimals: 3
    device_class: monetary
    update_interval: never

  - platform: template
    name: 'Cost Daily Average'
    icon: mdi:cash-100
    id: cost_daily_avg_sensor
    accuracy_decimals: 3
    unit_of_measurement: $currency
    device_class: monetary
    update_interval: never

  - platform: template
    name: 'Usage Daily Average'
    icon: mdi:meter-electric
    id: usage_daily_avg_sensor
    accuracy_decimals: 3
    unit_of_measurement: 'kWh'
    device_class: energy
    update_interval: never

  - platform: template
    name: 'Uptime'
    icon: mdi:timelapse
    id: uptime_sensor
    accuracy_decimals: 2
    unit_of_measurement: 'days'
    update_interval: never

time:
  - platform: homeassistant
    id: esp_time

interval:
  - interval: 1s
    then:
      lambda: |-
        static uint32_t update_count = 0;
        static uint32_t last_day_of_year = 0;
        static uint32_t last_month = 0;
        auto time = id(esp_time).now();
        if ( time.is_valid() )
        {
          if ( time.day_of_year != last_day_of_year ) {
            if (last_day_of_year != 0) {
              id(op_flag) |= $flag_reset_daily;
            }
            last_day_of_year = time.day_of_year;
          }
          if ( time.month != last_month ) {
            if (last_month != 0) {
              id(op_flag) |= $flag_reset_monthly;
            }
            last_month = time.month;
          }
        }        
        if ( id(op_flag) & $flag_reset_total ) {
          ESP_LOGD("debug", "reset total");
          id(uptime_start) = 0;
          id(uptime_secs) = 0;
          id(usage_total) = 0;
          id(cost_total) = 0;
          id(cost_now) = 0;
          update_count = 0;
        }
        if ( id(op_flag) & $flag_reset_daily ) {
          ESP_LOGD("debug", "reset daily");
          id(usage_day) = 0;
          id(cost_day) = 0;
          update_count = 0;
        }
        if ( id(op_flag) & $flag_reset_monthly ) {
          ESP_LOGD("debug", "reset monthly");
          id(usage_month) = 0;
          id(cost_month) = 0;
          update_count = 0;
        }
        if ( time.is_valid() ) {
          if (update_count == 0) {
            id(op_flag) |= $flag_update_sensors;
          }
          update_count++;
          if ( update_count >= $update_interval ) {
            update_count = 0;
          }
          if ( id(op_flag) & $flag_update_sensors ) {
            float days = 0;
            if ( id(uptime_start) == 0 ) {
              id(uptime_start) = time.timestamp - id(uptime_secs);
            }
            else if ( ( time.timestamp - id(uptime_start) ) > id(uptime_secs) ) {
              id(uptime_secs) = time.timestamp - id(uptime_start);
            }
            if ( id(uptime_secs) > 0 ) {
              days = id(uptime_secs) / 60.0f / 60.0f / 24.0f;
            }
            id(uptime_sensor).publish_state(days);
            if ( days < 1.0 ) {
              days = 1.0;   // welcome to kludgeville, but otherwise we'll get crazy high daily averages with uptimes less than 1 day
            }
            id(usage_daily_avg_sensor).publish_state(id(power_pulse_total).state / days);           
            id(cost_daily_avg_sensor).publish_state(id(cost_total) / days);
            id(usage_day_sensor).publish_state( id(usage_day) );
            id(cost_day_sensor).publish_state( id(cost_day) );
            
            id(usage_month_sensor).publish_state( id(usage_month) );
            id(cost_month_sensor).publish_state( id(cost_month) );
            if ( id(op_flag) & $flag_reset_total )            
            {
              id(usage_total_sensor).publish_state(id(usage_total));
              id(cost_total_sensor).publish_state(id(cost_total));
              id(cost_now_sensor).publish_state(id(cost_now));
            }
          }
        }
        id(op_flag) = 0;         // making sure the flag operations are one-shot

script:
  - id: process_power_script
    mode: single
    then:
      lambda: |-
        // Methods of counting. Left, Right or Trapezoid. Only one used here is Right
        // energy = delta_hours * old_state;                        // Left
        // energy = delta_hours * new_state;                        // Right
        // energy = delta_hours * (old_state + new_state) / 2.0;    // Trapezoid
        static uint32_t last_pulse_ms = 0;
        const uint32_t now = millis();
        // we wont process the very first pulse, as we have no idea how long ago the last one was,
        if (last_pulse_ms == 0) {
          last_pulse_ms = now;
          return;
        }
        // calculate hours since last pulse
        const float delta_hours = (now - last_pulse_ms) / 1000.0f / 60.0f / 60.0f;
        last_pulse_ms = now;    // remember last pulse milliseconds
        // get the power state in kWh
        float new_state = id(power_pulse_meter).state / 1000.0f;

        // calculate energy consumption and cost
        const float energy = delta_hours * new_state;
        const float cost = energy * id(price_per_kwh);
        id(usage_total) += energy;
        id(usage_day) += energy;
        id(usage_month) += energy;
        id(cost_total) += cost;
        id(cost_day) += cost;
        id(cost_month) += cost;

        // calculate current hourly cost
        //ESP_LOGD("debug", "Power: %.3f - Price: %.3f", new_state, id(price_per_kwh));
        id(cost_now) = new_state * id(price_per_kwh);

        // publish states to the sensors we want 'live' updates on (the rest can wait for the update_interval)
        id(usage_total_sensor).publish_state(id(usage_total));
        id(cost_total_sensor).publish_state(id(cost_total));
        id(cost_now_sensor).publish_state(id(cost_now));

        // if you uncomment the following you'll also update the rest of the sensors at each pulse (in the interval).
        // id(op_flag) |= $flag_update_sensors;

        // if LED is on, set the color
        if (id(power_led).current_values.is_on()) {
          id(set_power_led_script).execute();
        }

  - id: set_power_led_script
    mode: restart
    then:
      lambda: |-
        const float s = 1.0;    // saturation (purity). [0-1]
        const float v = 0.5;    // brightness. [0-1]
        int i;
        float r, g, b, f, h, p, q, t;
        f = id(power_pulse_meter).state * 100 / id(power_problem_level).state;
        if (f < 100) {
          h = 130 - f;    // orange to green
        } else {
          f -= 100;
          if (f == 0) {
            h = 0;        // red
          } else if (f > 120) {
            h = 300;      // purple
          } else {
            h = 360 - ceil(f / 2.0);  // red to purple
          }
        }
        h /= 60;   // sector 0 to 5
        i = floor(h);
        f = h - i;
        p = v * ( 1 - s );
        q = v * ( 1 - s * f );
        t = v * ( 1 - s * ( 1 - f ) );
        switch( i ) {
          case 0:
            r = v;
            g = t;
            b = p;
            break;
          case 1:
            r = q;
            g = v;
            b = p;
            break;
          case 2:
            r = p;
            g = v;
            b = t;
            break;
          case 3:
            r = p;
            g = q;
            b = v;
            break;
          case 4:
            r = t;
            g = p;
            b = v;
            break;
          default:
            r = v;
            g = p;
            b = q;
            break;
        }
        auto call = id(power_led).turn_on();
        //call.set_brightness(0.4);
        call.set_rgb(r, g, b);
        call.perform();

